/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AlunosRouteImport } from './routes/alunos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InboxCoordenadorRouteImport } from './routes/inbox.coordenador'
import { Route as InboxAvaliadorRouteImport } from './routes/inbox.avaliador'
import { Route as DashboardAlunoRouteImport } from './routes/dashboard.aluno'
import { Route as DashboardAlunoContratoProcessoIdRouteImport } from './routes/dashboard.aluno.contrato.$processoId'
import { Route as DashboardAlunoRelatorioProcessoIdRelatorioIdRouteImport } from './routes/dashboard.aluno.relatorio.$processoId.$relatorioId'

const AlunosRoute = AlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxCoordenadorRoute = InboxCoordenadorRouteImport.update({
  id: '/inbox/coordenador',
  path: '/inbox/coordenador',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxAvaliadorRoute = InboxAvaliadorRouteImport.update({
  id: '/inbox/avaliador',
  path: '/inbox/avaliador',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAlunoRoute = DashboardAlunoRouteImport.update({
  id: '/dashboard/aluno',
  path: '/dashboard/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAlunoContratoProcessoIdRoute =
  DashboardAlunoContratoProcessoIdRouteImport.update({
    id: '/contrato/$processoId',
    path: '/contrato/$processoId',
    getParentRoute: () => DashboardAlunoRoute,
  } as any)
const DashboardAlunoRelatorioProcessoIdRelatorioIdRoute =
  DashboardAlunoRelatorioProcessoIdRelatorioIdRouteImport.update({
    id: '/relatorio/$processoId/$relatorioId',
    path: '/relatorio/$processoId/$relatorioId',
    getParentRoute: () => DashboardAlunoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/dashboard/aluno': typeof DashboardAlunoRouteWithChildren
  '/inbox/avaliador': typeof InboxAvaliadorRoute
  '/inbox/coordenador': typeof InboxCoordenadorRoute
  '/dashboard/aluno/contrato/$processoId': typeof DashboardAlunoContratoProcessoIdRoute
  '/dashboard/aluno/relatorio/$processoId/$relatorioId': typeof DashboardAlunoRelatorioProcessoIdRelatorioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/dashboard/aluno': typeof DashboardAlunoRouteWithChildren
  '/inbox/avaliador': typeof InboxAvaliadorRoute
  '/inbox/coordenador': typeof InboxCoordenadorRoute
  '/dashboard/aluno/contrato/$processoId': typeof DashboardAlunoContratoProcessoIdRoute
  '/dashboard/aluno/relatorio/$processoId/$relatorioId': typeof DashboardAlunoRelatorioProcessoIdRelatorioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/dashboard/aluno': typeof DashboardAlunoRouteWithChildren
  '/inbox/avaliador': typeof InboxAvaliadorRoute
  '/inbox/coordenador': typeof InboxCoordenadorRoute
  '/dashboard/aluno/contrato/$processoId': typeof DashboardAlunoContratoProcessoIdRoute
  '/dashboard/aluno/relatorio/$processoId/$relatorioId': typeof DashboardAlunoRelatorioProcessoIdRelatorioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alunos'
    | '/dashboard/aluno'
    | '/inbox/avaliador'
    | '/inbox/coordenador'
    | '/dashboard/aluno/contrato/$processoId'
    | '/dashboard/aluno/relatorio/$processoId/$relatorioId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alunos'
    | '/dashboard/aluno'
    | '/inbox/avaliador'
    | '/inbox/coordenador'
    | '/dashboard/aluno/contrato/$processoId'
    | '/dashboard/aluno/relatorio/$processoId/$relatorioId'
  id:
    | '__root__'
    | '/'
    | '/alunos'
    | '/dashboard/aluno'
    | '/inbox/avaliador'
    | '/inbox/coordenador'
    | '/dashboard/aluno/contrato/$processoId'
    | '/dashboard/aluno/relatorio/$processoId/$relatorioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlunosRoute: typeof AlunosRoute
  DashboardAlunoRoute: typeof DashboardAlunoRouteWithChildren
  InboxAvaliadorRoute: typeof InboxAvaliadorRoute
  InboxCoordenadorRoute: typeof InboxCoordenadorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/alunos': {
      id: '/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/coordenador': {
      id: '/inbox/coordenador'
      path: '/inbox/coordenador'
      fullPath: '/inbox/coordenador'
      preLoaderRoute: typeof InboxCoordenadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/avaliador': {
      id: '/inbox/avaliador'
      path: '/inbox/avaliador'
      fullPath: '/inbox/avaliador'
      preLoaderRoute: typeof InboxAvaliadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/aluno': {
      id: '/dashboard/aluno'
      path: '/dashboard/aluno'
      fullPath: '/dashboard/aluno'
      preLoaderRoute: typeof DashboardAlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/aluno/contrato/$processoId': {
      id: '/dashboard/aluno/contrato/$processoId'
      path: '/contrato/$processoId'
      fullPath: '/dashboard/aluno/contrato/$processoId'
      preLoaderRoute: typeof DashboardAlunoContratoProcessoIdRouteImport
      parentRoute: typeof DashboardAlunoRoute
    }
    '/dashboard/aluno/relatorio/$processoId/$relatorioId': {
      id: '/dashboard/aluno/relatorio/$processoId/$relatorioId'
      path: '/relatorio/$processoId/$relatorioId'
      fullPath: '/dashboard/aluno/relatorio/$processoId/$relatorioId'
      preLoaderRoute: typeof DashboardAlunoRelatorioProcessoIdRelatorioIdRouteImport
      parentRoute: typeof DashboardAlunoRoute
    }
  }
}

interface DashboardAlunoRouteChildren {
  DashboardAlunoContratoProcessoIdRoute: typeof DashboardAlunoContratoProcessoIdRoute
  DashboardAlunoRelatorioProcessoIdRelatorioIdRoute: typeof DashboardAlunoRelatorioProcessoIdRelatorioIdRoute
}

const DashboardAlunoRouteChildren: DashboardAlunoRouteChildren = {
  DashboardAlunoContratoProcessoIdRoute: DashboardAlunoContratoProcessoIdRoute,
  DashboardAlunoRelatorioProcessoIdRelatorioIdRoute:
    DashboardAlunoRelatorioProcessoIdRelatorioIdRoute,
}

const DashboardAlunoRouteWithChildren = DashboardAlunoRoute._addFileChildren(
  DashboardAlunoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlunosRoute: AlunosRoute,
  DashboardAlunoRoute: DashboardAlunoRouteWithChildren,
  InboxAvaliadorRoute: InboxAvaliadorRoute,
  InboxCoordenadorRoute: InboxCoordenadorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
